{
  "navbarLinks":
    [{ text: "Home", href: "/" }, { text: "Portfolio", href: "/portfolio" }, { text: "CV", href: "CV" }, { text: "About", href: "/about" }],
  "home": { "whoAmI": { "language": "html", "content": "<p>
            My name is Kaappo, I'm 18 years old and I currently I study at Otaniemi Upper Secondary School at their
            mathematics and science program. I have programmed since I was six, and thus programming is very close
            to my heart. Despite my relatively young age, I have a lot of experience developing software, both
            professionally and for fun.
            </p>
            <p>
            In addition to programming, my hobbies include photography, all event technology -related matters, and
            playing the guitar.
            </p>" } },
  "portfolio":
    [
      {
        "title": "Scientia",
        "coverImage":
          {
            "src": "/public/res/concept1.webp",
            "alt": "Boat instruments in a grid",
          },
        "logo": { "src": "public/res/scientia-logo.svg" },
        "previewText": { "language": "html", "content": '<p>Scientia (<code>/ˈsaɪənˌtɪa/</code>) is a boat instrumentation system which uses an open
              standard, <a href="https://signalk.org/">Signal K</a> as its data source. It''s capable of
              displaying data from a <a href="https://github.com/SignalK/signalk-server">Signal K server</a>
              in a clear and uncluttered way.</p>' },
      },
      {
        "title": "WilmaInk",
        "coverImage":
          {
            "src": "/public/res/1.webp",
            "alt": "My school note on as it would be shown on an e-ink display",
          },
        "logo": { "src": "public/res/wilmaink.svg" },
        "previewText":
          { "language": "html", "content": "<p>WilmaInk is a sister of my other project Wilmacrawler, which it uses as a back-end. WilmaInk
              presents the data in a form that can be rendered on an e-ink display. This means limited resution, and very limited color palette, in my e-ink display's case 3 colors:
              black, white, and red.</p>" },
      },
    ],
  "cv":
    {
      experience:
        [
          {
            title: "The Finnish National Opera",
            subtitle: "Children's choir singer and actor",
            cornerNote: "Aug 2013 (10yo) – May 2015 (12yo)",
            description: { language: "html", content: "The only professional-level children's choir in Finland." },
            role: "secondary",
          },
          {
            title: "Accenture Technology Solutions",
            subtitle: "Application Development Associate",
            cornerNote: "Jun 2019 (at 16yo)",
            note: "full-time (summer job)",
            description:
              {
                language: "html",
                "content": "As a member of the R&D team, I programmed an indoors navigation stack for a robot used by Accenture for promotion purposes",
              },
            role: "secondary",
          },
          {
            title: "Accenture Technology Solutions",
            subtitle: "Application Development New Associate",
            cornerNote: "Jun 2021 – Aug 2021 (at 18yo)",
            note: "full-time (summer job)",
            description: { language: "html", "content": "During the summer my tasks included:
                  <ul>
                  <li>Writing an asset processing pipeline for a 3D simulator</li>
                  <li>Creating an HTTPS wrapper for a legacy c++ SDK</li>
                  <li>Writing a lot of specifications for delegation to subcontractors</li>
                  </ul>" },
          },
          {
            title: "Tmi Kaappo Raivio",
            subtitle: "Entrepreneur",
            note: "part-time",
            cornerNote: "Feb 2021 –",
            description:
              { language: "html", content: "Through my trade name (toiminimi), I sell licenses to my photographs and do small photographing gigs." },
            role: "primary",
          },
          {
            title: "Accenture Technology Solutions",
            subtitle: "Application Development Analyst",
            cornerNote: "Sep 2021 – ",
            note: "part-time",
            description: { language: "html", "content": "I work part-time while studying my final year at Otaniemi upper secondary school.
                  My tasks consist of generic software development and system integration." },
            role: "primary",
          },
        ],
      education:
        [
          {
            title: "Päivänkehrä elementary school",
            subtitle: "",
            cornerNote: "Aug 2010 – Jun 2016",
            description: { language: "html", content: "" },
            role: "secondary",
          },
          {
            title: "Olari Lower Secondary School",
            subtitle: "Mathematics and science program",
            cornerNote: "Aug 2016 – Jun 2019",
            description:
              {
                language: "html",
                content: '<p>GPA of 9.54, <a href="https://opintopolku.fi/koski/opinnot/aa55dd30c8f9494cade289992adc3738"><u>Link to my diploma (in Finnish)</u></a></p>',
              },
          },
          {
            title: "Otaniemi Upper Secondary School",
            subtitle: "Mathematics and science program",
            cornerNote: "Aug 2019 – Jun 2022 (expected)",
            description: { language: "html", content: "<p>
                  Also, a few completed programming courses at Aalto University through collaboration with them
                  </p>" },
            role: "primary",
          },
        ],
      skills:
        [
          {
            color: "green",
            content:
              ['<acronym title="Hypertext Markup Language">HTML</acronym>', '<acronym title="Cascading stylesheets">CSS</acronym>', "JavaScript"],
          },
          { color: "#004752", content: ["python", "java", "c++"] },
          { color: "blue", content: ["node", "express", "react"] },
          {
            color: "red",
            content:
              [
                "Android",
                '<acronym title="Universal Windows Platform">UWP</acronym>',
                "Hololens",
                '<acronym title="High level architecture">HLA</acronym>',
              ],
          },
          { color: "gray", content: ["git", "github", "linux"] },
        ],
      competitions: [],
      volunteerWork:
        [
          {
            title: "Event technician",
            description: { language: "html", content: 'A student-lead technician team from our upper secondary is responsible for providing event
                  tech for most of the events of the school. You can find photos
                  <a href="https://olariav.pixieset.com/olariav/" target="_blank">of our accomplishments here</a>' },
            cornerNote: "Aug 2019 –",
          },
        ],
    },
}
